GET http://localhost:3000/authtest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibG9naW4iOiJTa3Vyc29uIiwiaWF0IjoxNzMxOTQyNjAyLCJleHAiOjE3MzE5NDM1MDJ9.4FkYDDmY11VWmGHomXmH0ld-1aFIy2_fmBYyUAkbm3M

###
POST http://localhost:3000/token
Content-Type: application/json

{
  "refreshToken":
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImZvbyIsImlhdCI6MTczMTUyNDQwMCwiZXhwIjoxNzMyMTI5MjAwfQ.tdLF1phuDcfgiXCDMiYJ5LOzCYg2w-56-jaS7JZ1Ssk"
}

###
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "login": "Skurson",
  "password": "skura"
}

###
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "login": "foo",
  "password": "foo"
}

###

POST http://localhost:3000/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibG9naW4iOiJmb28iLCJpYXQiOjE3MzE5NDAzOTYsImV4cCI6MTczMTk0MTI5Nn0.R3it0MFx4bymx-KgArYg2laEO_TeTkd57LFEH8hkoLo

###
GET http://localhost:3000/cart/numberof
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibG9naW4iOiJ0b3JiaSIsImlhdCI6MTczMzY4MDg0MywiZXhwIjoxNzMzNjgxNzQzfQ.hngIKH1tQJVDzNKbQ7ojqbiM1Rc-2dIoUjGy5FuaigQ